version: '3.3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=ecs,iam,cloudwatch,logs,sts,ec2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack:/tmp/localstack"
